defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Nayoung Choi
subtitle: Ph.D. student in Computer Science<br>@ SCHOOL

left_side:
  background_image: "./assets/images/cats.jpeg"
  background_color: "#484848"
  close_button_color: "#000000"
  text_color: "#000000"

footer:
  copyright_text: "&copy; Nayoung Choi"

# Side Menu Links
menu:
  - text: About
    link: /
    icon: ""

  - text: Publications
    link: /publications
    icon: ""

  #- text: Contact Me
  #  link: /contact
  #  icon: ""

  #- text: My Resume
  #  link: /resume
  #  icon: ""

  #- text: Blog Posts
  #  link: /blog
  #  icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/nayoung-%E2%80%8Dchoi-b6b6a9202/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/nayoung-choi
    icon: fab fa-github-square

  #- name: facebook
  #  link: https://www.facebook.com/christian.ezeani.cyb
  #  icon: fab fa-facebook-square

  #- name: twitter
  #  link: https://www.twitter.com/christianezeani
  #  icon: fab fa-twitter


    
