remote_theme: christianezeani/panthera-jekyll

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Nayoung Choi
subtitle: Ph.D. student in Computer Science<br>@ {SCHOOL}

left_side:
  background_image: "./assets/images/cats.jpeg"
  background_color: "#484848"
  close_button_color: "#000000"
  text_color: "#FFFFFF"

footer:
  copyright_text: "&copy; Nayoung Choi"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: google scholar
    link: https://scholar.google.com/citations?user=0JoEIaEAAAAJ
    icon: fas fa-user-graduate

  - name: github
    link: https://github.com/nayoung-choi
    icon: fab fa-github-square

  - name: linkedin
    link: https://www.linkedin.com/in/nayoung-%E2%80%8Dchoi-b6b6a9202/
    icon: fab fa-linkedin

  - name: twitter
    link: https://twitter.com/nayoung_ch70376
    icon: fab fa-twitter
